name: neom_google_places
description: Google places autocomplete widgets for flutter maintained by Cyberneom.
version: 1.2.0
repository: https://github.com/Cyberneom/neom_google_places

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  google_api_headers: ^4.6.2
  neom_maps_services: ^1.1.0
  http: ^1.5.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  assets:
    - packages/neom_google_places/assets/google_black.png
    - packages/neom_google_places/assets/google_white.png
