name: neom_google_places
description: Google places autocomplete widgets for flutter maintained by Open Neom.
version: 2.0.1
repository: https://github.com/Cyberneom/neom_google_places

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  google_api_headers: ^5.0.1
  neom_maps_services: ^2.0.0
  http: ^1.6.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
